=== Shella49/json_dz/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "type": "string"
            },
            "path": {
                "type": "string"
            },
            "size": {
                "type": "integer"
            },
            "creation_date": {
                "type": "string",
                "format": "date-time"
            },
            "modification_date": {
                "type": "string",
                "format": "date-time"
            }
        },
        "required": [
            "name",
            "path",
            "size",
            "creation_date",
            "modification_date"
        ]
    }
}

=== Shella49/json_dz/files_info.json
[
    {
        "name": "english_processed.txt",
        "path": "D:\\Ucheba\\PYTHON\\УрокиПитон\\json\\Json_dz\\project_root\\data\\processed\\english_processed.txt",
        "size": 73,
        "creation_date": "2024-11-30T16:29:50.754956",
        "modification_date": "2024-11-30T16:29:50.757956"
    },
    {
        "name": "france_processed.txt",
        "path": "D:\\Ucheba\\PYTHON\\УрокиПитон\\json\\Json_dz\\project_root\\data\\processed\\france_processed.txt",
        "size": 62,
        "creation_date": "2024-11-30T16:29:50.762957",
        "modification_date": "2024-11-30T16:29:50.766957"
    },
    {
        "name": "russian_processed.txt",
        "path": "D:\\Ucheba\\PYTHON\\УрокиПитон\\json\\Json_dz\\project_root\\data\\processed\\russian_processed.txt",
        "size": 130,
        "creation_date": "2024-11-30T16:29:50.773957",
        "modification_date": "2024-11-30T16:29:50.776958"
    }
]
